In [36]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv


In [37]:
titanic = pd.read_csv('/kaggle/input/titanic/train.csv')

df_train = pd.DataFrame(titanic)


pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns


df_train


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
30            31         0       1   
31            32         1       1   
32            33         1       3   
33            34         0       2   
34            35         0       1   
35            36         0       1   
36            37         1       3   
37            38         0       3   
38            39         0       3   
39            40         1       3   
40            41         0       3   
41            42         0       2   
42            43         0       3   
43            44         1       2   
44            45         1       3   
45            46         0       3   
46            47         0       3   
47            48         1       3   
48            49         0       3   
49            50         0       3   
50            51         0       3   
51            52         0       3   
52            53         1       1   
53            54         1       2   
54            55         0       1   
55            56         1       1   
56            57         1       2   
57            58         0       3   
58            59         1       2   
59            60         0       3   
60            61         0       3   
61            62         1       1   
62            63         0       1   
63            64         0       3   
64            65         0       1   
65            66         1       3   
66            67         1       2   
67            68         0       3   
68            69         1       3   
69            70         0       3   
70            71         0       2   
71            72         0       3   
72            73         0       2   
73            74         0       3   
74            75         1       3   
75            76         0       3   
76            77         0       3   
77            78         0       3   
78            79         1       2   
79            80         1       3   
80            81         0       3   
81            82         1       3   
82            83         1       3   
83            84         0       1   
84            85         1       2   
85            86         1       3   
86            87         0       3   
87            88         0       3   
88            89         1       1   
89            90         0       3   
90            91         0       3   
91            92         0       3   
92            93         0       1   
93            94         0       3   
94            95         0       3   
95            96         0       3   
96            97         0       1   
97            98         1       1   
98            99         1       2   
99           100         0       2   
100          101         0       3   
101          102         0       3   
102          103         0       1   
103          104         0       3   
104          10

In [39]:
df_train.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [40]:
print(df_train['Age'].value_counts())

24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
30.00    25
21.00    24
25.00    23
36.00    22
29.00    20
32.00    18
35.00    18
27.00    18
26.00    18
16.00    17
31.00    17
20.00    15
34.00    15
33.00    15
23.00    15
39.00    14
40.00    13
17.00    13
42.00    13
45.00    12
38.00    11
50.00    10
2.00     10
4.00     10
44.00     9
48.00     9
47.00     9
54.00     8
9.00      8
1.00      7
51.00     7
14.00     6
52.00     6
37.00     6
49.00     6
41.00     6
3.00      6
58.00     5
15.00     5
43.00     5
62.00     4
56.00     4
5.00      4
11.00     4
60.00     4
8.00      4
6.00      3
46.00     3
61.00     3
65.00     3
7.00      3
10.00     2
64.00     2
13.00     2
63.00     2
30.50     2
57.00     2
70.00     2
0.75      2
71.00     2
59.00     2
0.83      2
40.50     2
55.00     2
32.50     2
28.50     2
45.50     2
34.50     1
0.42      1
0.67      1
66.00     1
24.50     1
80.00     1
20.50     1
53.00     1
14.50     1
70.50     1
12.00     1
36.5

# Dataset 1

Dropping     Cabin, Ticket, Name.

In [41]:
pd.set_option('display.max_rows', 4)  # Show all rows

df_train1 = df_train

df_train1.drop(columns = ['Cabin', 'Ticket', 'Name'], axis=1, inplace=True)

df_train1


PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    male  22.0      1      0   7.2500   
1              2         1       1  female  38.0      1      0  71.2833   
..           ...       ...     ...     ...   ...    ...    ...      ...   
889          890         1       1    male  26.0      0      0  30.0000   
890          891         0       3    male  32.0      0      0   7.7500   

    Embarked  
0          S  
1          C  
..       ...  
889        C  
890        Q  

[891 rows x 9 columns]

In [42]:
df_train1['Embarked'].fillna('S', inplace=True)

In [43]:
df_train1['Sex'] = df_train1['Sex'].map({'male': 1, 'female': 2})    # male=1 female=2

df_train1

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0              1         0       3    1  22.0      1      0   7.2500        S
1              2         1       1    2  38.0      1      0  71.2833        C
..           ...       ...     ...  ...   ...    ...    ...      ...      ...
889          890         1       1    1  26.0      0      0  30.0000        C
890          891         0       3    1  32.0      0      0   7.7500        Q

[891 rows x 9 columns]

In [44]:
df_train1['Embarked'] = df_train1['Embarked'].map({'S': 1, 'C': 2, 'Q': 3})

df_train1   # Two NaN in Embarked column... index 61 829 both survived

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0              1         0       3    1  22.0      1      0   7.2500         1
1              2         1       1    2  38.0      1      0  71.2833         2
..           ...       ...     ...  ...   ...    ...    ...      ...       ...
889          890         1       1    1  26.0      0      0  30.0000         2
890          891         0       3    1  32.0      0      0   7.7500         3

[891 rows x 9 columns]

In [45]:
#Handling missing age

df_train1_age_Na = df_train1[df_train1['Age'].isna()]

df_train1 = df_train1.dropna(subset=['Age'])

In [46]:
df_train1_age_Na

PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch     Fare  Embarked
5              6         0       3    1  NaN      0      0   8.4583         3
17            18         1       2    1  NaN      0      0  13.0000         1
..           ...       ...     ...  ...  ...    ...    ...      ...       ...
878          879         0       3    1  NaN      0      0   7.8958         1
888          889         0       3    2  NaN      1      2  23.4500         1

[177 rows x 9 columns]

In [47]:
df_train1

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0              1         0       3    1  22.0      1      0   7.2500         1
1              2         1       1    2  38.0      1      0  71.2833         2
..           ...       ...     ...  ...   ...    ...    ...      ...       ...
889          890         1       1    1  26.0      0      0  30.0000         2
890          891         0       3    1  32.0      0      0   7.7500         3

[714 rows x 9 columns]

In [151]:
#Model to predict age.

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler


df_train1_age = df_train1

X_age = df_train1_age.drop(columns = ['Age', 'PassengerId'])
y_age = df_train1_age['Age']

scaler = StandardScaler()

X_age_scaled = scaler.fit_transform(X_age)
y_age_scaled = scaler.fit_transform(y_age.values.reshape(-1, 1)).ravel()

X_train, X_test, y_train, y_test = train_test_split(X_age_scaled, y_age_scaled, test_size = 0.2,random_state = 28)

model = RandomForestRegressor(n_estimators=1800, random_state=28)
model.fit(X_train, y_train)


y_pred = model.predict(X_test)


'''
# Reshape y_pred_scaled and y_test to 2D arrays
y_pred = y_pred.reshape(-1, 1)
y_test_scaled = y_test.reshape(-1, 1)

# Inverse transform the predicted 'Age' values and the true 'Age' values to the original scale
y_pred = scaler.inverse_transform(y_pred).ravel()
y_true = scaler.inverse_transform(y_test_scaled).ravel()
'''

y_pred = y_pred.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)


y_pred = scaler.inverse_transform(y_pred)
y_test = scaler.inverse_transform(y_test)



mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("R-squared:", r2)



Mean Absolute Error: 9.05054520619533
Mean Squared Error: 139.2252424877427
R-squared: 0.36539472015248764


In [152]:
y_pred


array([[23.8813484 ],
       [26.54737566],
       [10.91321158],
       [22.05947717],
       [38.74166799],
       [28.24111111],
       [45.88444444],
       [37.72166667],
       [31.8126554 ],
       [55.17350463],
       [32.40312887],
       [24.74087615],
       [28.29222429],
       [28.66613095],
       [34.85261111],
       [28.29222429],
       [10.76351852],
       [21.32506746],
       [28.29222429],
       [29.22321847],
       [30.66621339],
       [30.03928704],
       [42.07558333],
       [44.12718334],
       [34.29611111],
       [10.91321158],
       [30.66621339],
       [32.1794545 ],
       [44.51304365],
       [34.76432659],
       [16.2599463 ],
       [33.04221951],
       [12.80695701],
       [33.9280873 ],
       [45.03644577],
       [40.06311055],
       [38.29840741],
       [34.21587018],
       [36.18553704],
       [30.69488532],
       [26.45881481],
       [31.42369312],
       [10.91321158],
       [14.26037685],
       [ 3.24153704],
       [32

In [126]:
y_test

array([[25.  ],
       [32.  ],
       [14.  ],
       [20.  ],
       [70.  ],
       [41.  ],
       [71.  ],
       [32.  ],
       [19.  ],
       [27.  ],
       [35.  ],
       [22.  ],
       [26.  ],
       [18.  ],
       [47.  ],
       [26.  ],
       [33.  ],
       [22.  ],
       [19.  ],
       [25.  ],
       [25.  ],
       [16.  ],
       [71.  ],
       [30.  ],
       [56.  ],
       [ 9.  ],
       [25.  ],
       [34.  ],
       [28.  ],
       [18.  ],
       [13.  ],
       [23.  ],
       [21.  ],
       [33.  ],
       [24.  ],
       [34.  ],
       [36.  ],
       [25.  ],
       [17.  ],
       [27.  ],
       [43.  ],
       [10.  ],
       [ 1.  ],
       [18.  ],
       [20.  ],
       [21.  ],
       [39.  ],
       [ 4.  ],
       [34.  ],
       [30.  ],
       [ 9.  ],
       [20.  ],
       [36.5 ],
       [65.  ],
       [16.  ],
       [36.  ],
       [25.  ],
       [18.  ],
       [35.  ],
       [ 9.  ],
       [22.  ],
       [31.  ],
       [

In [153]:
y_pred_round = np.round(y_pred)

y_pred_round

array([[24.],
       [27.],
       [11.],
       [22.],
       [39.],
       [28.],
       [46.],
       [38.],
       [32.],
       [55.],
       [32.],
       [25.],
       [28.],
       [29.],
       [35.],
       [28.],
       [11.],
       [21.],
       [28.],
       [29.],
       [31.],
       [30.],
       [42.],
       [44.],
       [34.],
       [11.],
       [31.],
       [32.],
       [45.],
       [35.],
       [16.],
       [33.],
       [13.],
       [34.],
       [45.],
       [40.],
       [38.],
       [34.],
       [36.],
       [31.],
       [26.],
       [31.],
       [11.],
       [14.],
       [ 3.],
       [32.],
       [37.],
       [ 7.],
       [32.],
       [28.],
       [ 6.],
       [24.],
       [37.],
       [34.],
       [10.],
       [31.],
       [43.],
       [28.],
       [27.],
       [ 4.],
       [37.],
       [37.],
       [33.],
       [20.],
       [40.],
       [21.],
       [30.],
       [35.],
       [58.],
       [ 2.],
       [30.],
      

In [54]:
# now for the missing data.

y_pred_train1 = 

SyntaxError: invalid syntax (862315830.py, line 3)

In [154]:
#Grid Search:
#Grid search exhaustively searches through a specified set of hyperparameter combinations. Here's how you can use grid search:

#Randomized Search:
#Randomized search explores a random subset of the hyperparameter space. This can be more efficient when the hyperparameter space is large.